use std::collections::HashMap;

use orbitdock_protocol::{
    ApprovalType, ClaudeModelOption, McpAuthStatus, McpResource, McpResourceTemplate,
    McpStartupFailure, McpStartupStatus, McpTool, RemoteSkillSummary, SkillErrorInfo,
    SkillsListEntry, TokenUsage, TokenUsageSnapshotKind,
};

/// Events emitted by connectors
#[derive(Debug, Clone)]
pub enum ConnectorEvent {
    /// Turn started
    TurnStarted,

    /// Turn completed
    TurnCompleted,

    /// Turn aborted
    TurnAborted { reason: String },

    /// New message created
    MessageCreated(orbitdock_protocol::Message),

    /// Message updated
    MessageUpdated {
        message_id: String,
        content: Option<String>,
        tool_output: Option<String>,
        is_error: Option<bool>,
        is_in_progress: Option<bool>,
        duration_ms: Option<u64>,
    },

    /// Approval requested
    ApprovalRequested {
        request_id: String,
        approval_type: ApprovalType,
        tool_name: Option<String>,
        tool_input: Option<String>,
        command: Option<String>,
        file_path: Option<String>,
        diff: Option<String>,
        question: Option<String>,
        proposed_amendment: Option<Vec<String>>,
    },

    /// Approval cancelled by the CLI (e.g. user interrupted, agent moved on)
    ApprovalCancelled { request_id: String },

    /// Permission mode changed (e.g. plan mode entered/exited)
    PermissionModeChanged { mode: String },

    /// Token usage updated
    TokensUpdated {
        usage: TokenUsage,
        snapshot_kind: TokenUsageSnapshotKind,
    },

    /// Aggregated diff updated
    DiffUpdated(String),

    /// Plan updated
    PlanUpdated(String),

    /// Thread name updated (auto-generated by codex-core or manually set)
    ThreadNameUpdated(String),

    /// Session ended
    SessionEnded { reason: String },

    /// Skills list response
    SkillsList {
        skills: Vec<SkillsListEntry>,
        errors: Vec<SkillErrorInfo>,
    },

    /// Remote skills list response
    RemoteSkillsList { skills: Vec<RemoteSkillSummary> },

    /// Remote skill downloaded
    RemoteSkillDownloaded {
        id: String,
        name: String,
        path: String,
    },

    /// Skills update available notification
    SkillsUpdateAvailable,

    /// MCP tools list response
    McpToolsList {
        tools: HashMap<String, McpTool>,
        resources: HashMap<String, Vec<McpResource>>,
        resource_templates: HashMap<String, Vec<McpResourceTemplate>>,
        auth_statuses: HashMap<String, McpAuthStatus>,
    },

    /// MCP server startup progress update
    McpStartupUpdate {
        server: String,
        status: McpStartupStatus,
    },

    /// MCP server startup complete
    McpStartupComplete {
        ready: Vec<String>,
        failed: Vec<McpStartupFailure>,
        cancelled: Vec<String>,
    },

    /// Claude session initialized — carries capabilities from the init system message
    ClaudeInitialized {
        slash_commands: Vec<String>,
        skills: Vec<String>,
        tools: Vec<String>,
        models: Vec<ClaudeModelOption>,
    },

    /// Model name updated (e.g. from Claude init event)
    ModelUpdated(String),

    /// Context was compacted (summarized)
    ContextCompacted,

    /// Hook started with a (possibly new) session ID — used to register managed threads
    HookSessionId(String),

    /// Undo operation started
    UndoStarted { message: Option<String> },

    /// Undo operation completed
    UndoCompleted {
        success: bool,
        message: Option<String>,
    },

    /// Thread context was rolled back by N turns
    ThreadRolledBack { num_turns: u32 },

    /// Environment changed (cwd, git branch, git sha)
    EnvironmentChanged {
        cwd: Option<String>,
        git_branch: Option<String>,
        git_sha: Option<String>,
    },

    /// Rate limit event from the Claude SDK
    RateLimitEvent {
        info: orbitdock_protocol::RateLimitInfo,
    },

    /// Prompt suggestion from the Claude SDK
    PromptSuggestion { suggestion: String },

    /// Files were persisted (checkpoint saved)
    FilesPersisted { files: Vec<String> },

    /// Error occurred
    Error(String),
}
