//! OrbitDock Connectors
//!
//! Connectors for different AI providers (Claude, Codex).
//! Each connector handles communication with its respective provider
//! and translates events to the common OrbitDock protocol.

pub mod claude;
pub mod codex;

pub use claude::ClaudeConnector;
pub use codex::{discover_models, CodexConnector, SteerOutcome};
use orbitdock_protocol::{
    McpAuthStatus, McpResource, McpResourceTemplate, McpStartupFailure, McpStartupStatus, McpTool,
    TokenUsage, TokenUsageSnapshotKind,
};
use std::collections::HashMap;
use thiserror::Error;

/// Errors that can occur in connectors
#[derive(Debug, Error)]
pub enum ConnectorError {
    #[error("JSON serialization error: {0}")]
    JsonError(#[from] serde_json::Error),

    #[error("Channel closed")]
    ChannelClosed,

    #[error("Provider error: {0}")]
    ProviderError(String),
}

/// Events emitted by connectors
#[derive(Debug, Clone)]
pub enum ConnectorEvent {
    /// Turn started
    TurnStarted,

    /// Turn completed
    TurnCompleted,

    /// Turn aborted
    TurnAborted { reason: String },

    /// New message created
    MessageCreated(orbitdock_protocol::Message),

    /// Message updated
    MessageUpdated {
        message_id: String,
        content: Option<String>,
        tool_output: Option<String>,
        is_error: Option<bool>,
        is_in_progress: Option<bool>,
        duration_ms: Option<u64>,
    },

    /// Approval requested
    ApprovalRequested {
        request_id: String,
        approval_type: ApprovalType,
        tool_name: Option<String>,
        tool_input: Option<String>,
        command: Option<String>,
        file_path: Option<String>,
        diff: Option<String>,
        question: Option<String>,
        proposed_amendment: Option<Vec<String>>,
    },

    /// Token usage updated
    TokensUpdated {
        usage: TokenUsage,
        snapshot_kind: TokenUsageSnapshotKind,
    },

    /// Aggregated diff updated
    DiffUpdated(String),

    /// Plan updated
    PlanUpdated(String),

    /// Thread name updated (auto-generated by codex-core or manually set)
    ThreadNameUpdated(String),

    /// Session ended
    SessionEnded { reason: String },

    /// Skills list response
    SkillsList {
        skills: Vec<orbitdock_protocol::SkillsListEntry>,
        errors: Vec<orbitdock_protocol::SkillErrorInfo>,
    },

    /// Remote skills list response
    RemoteSkillsList {
        skills: Vec<orbitdock_protocol::RemoteSkillSummary>,
    },

    /// Remote skill downloaded
    RemoteSkillDownloaded {
        id: String,
        name: String,
        path: String,
    },

    /// Skills update available notification
    SkillsUpdateAvailable,

    /// MCP tools list response
    McpToolsList {
        tools: HashMap<String, McpTool>,
        resources: HashMap<String, Vec<McpResource>>,
        resource_templates: HashMap<String, Vec<McpResourceTemplate>>,
        auth_statuses: HashMap<String, McpAuthStatus>,
    },

    /// MCP server startup progress update
    McpStartupUpdate {
        server: String,
        status: McpStartupStatus,
    },

    /// MCP server startup complete
    McpStartupComplete {
        ready: Vec<String>,
        failed: Vec<McpStartupFailure>,
        cancelled: Vec<String>,
    },

    /// Claude session initialized — carries capabilities from the init system message
    ClaudeInitialized {
        slash_commands: Vec<String>,
        skills: Vec<String>,
        tools: Vec<String>,
        models: Vec<orbitdock_protocol::ClaudeModelOption>,
    },

    /// Model name updated (e.g. from Claude init event)
    ModelUpdated(String),

    /// Context was compacted (summarized)
    ContextCompacted,

    /// Hook started with a (possibly new) session ID — used to register managed threads
    HookSessionId(String),

    /// Undo operation started
    UndoStarted { message: Option<String> },

    /// Undo operation completed
    UndoCompleted {
        success: bool,
        message: Option<String>,
    },

    /// Thread context was rolled back by N turns
    ThreadRolledBack { num_turns: u32 },

    /// Environment changed (cwd, git branch, git sha)
    EnvironmentChanged {
        cwd: Option<String>,
        git_branch: Option<String>,
        git_sha: Option<String>,
    },

    /// Error occurred
    Error(String),
}

/// Type of approval request
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum ApprovalType {
    Exec,
    Patch,
    Question,
}
