const SF_TO_LUCIDE = {
  'terminal': 'Terminal',
  'terminal.fill': 'Terminal',
  'doc.plaintext': 'FileText',
  'doc.text': 'FileText',
  'pencil.line': 'Pencil',
  'pencil': 'Pencil',
  'magnifyingglass': 'Search',
  'globe': 'Globe',
  'globe.americas': 'Globe',
  'puzzlepiece.extension': 'Puzzle',
  'bolt.fill': 'Zap',
  'bolt': 'Zap',
  'questionmark.bubble': 'MessageCircleQuestion',
  'questionmark.circle': 'HelpCircle',
  'map': 'Map',
  'checklist': 'ListChecks',
  'arrow.triangle.2.circlepath': 'RefreshCw',
  'photo': 'Image',
  'bolt.badge.clock': 'Clock',
  'arrow.triangle.branch': 'GitBranch',
  'gearshape': 'Settings',
  'gearshape.fill': 'Settings',
  'person.fill': 'User',
  'brain': 'Brain',
  'bubble.left': 'MessageSquare',
  'exclamationmark.triangle': 'AlertTriangle',
  'shield': 'Shield',
  'hand.raised': 'Hand',
  'eye': 'Eye',
  'folder': 'Folder',
  'doc': 'File',
  'arrow.right.arrow.left': 'ArrowLeftRight',
  'network': 'Network',
  'cpu': 'Cpu',
  'link': 'Link',
  'text.alignleft': 'AlignLeft',
  'list.bullet': 'List',
  'square.and.pencil': 'FileEdit',
}

const getIconName = (sfSymbol) => SF_TO_LUCIDE[sfSymbol] || 'Circle'

export { SF_TO_LUCIDE, getIconName }
